export const SET_SUBMITTED_INPUT = "SET_SUBMITTED_INPUT";

export const LOAD_BOOKS = "LOAD_BOOKS";

export const LOAD_BOOKS_ON_SCROLL = "FETCH_BOOKS_ON_SCROLL";

export const ROTATE_SORT_ICON = "ROTATE_SORT_ICON";

export const SET_SELECT_VALUE = "SET_SELECT_VALUE";

export const SET_TOTAL_FETCHED_BOOKS = "SET_TOTAL_BOOKS";

export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";

export const ADD_TO_READ_LATER = "ADD_TO_READ_LATER";

export const REMOVE_FROM_READ_LATER = "REMOVE_FROM_READ_LATER";

export const SORT_READ_LATER_BOOKS = "SORT_READ_LATER_BOOKS";

export const SET_IS_FETCHING = "SET_IS_FETCHING";
